name: Data Processing and Model Training

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data processing and model training
        run: |
          python prediction_model.py  # Skrypt z modelami i analizą korelacji
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Zaktualizowana wersja upload-artifact
        with:
          name: results
          path: |
            Readme.pdf